### PR TITLE
Fix dependencies to be compatible with Elm 0.17

### PR DESCRIPTION
**Pull request by aluuu**

### CODE REVIEW

**Comment by aluuu** [comment]
Hi, @javcasas.

I think that it would be good idea to increase package version due to this changes. It would be very helpful during `elm-decimal` migration to elm 0.17.

**Comment by aluuu** [comment]
I've updated package version and would appreciate if you publish it ASAP.

**Comment by javcasas** [comment]
Sorry @aluuu, broke something while merging your pull request. I'll try again tomorrow, today it's too late for me to function properly.

**Comment by aluuu** [comment]
Ok, thanks for fast response. Waiting to see this package to appear in package repository 👍

**Pull request merged**
